site_name: Jupyter Sandbox Documentation

theme:
  name: "material"
  
plugins:
  - mkdocstrings

use_directory_urls: false


nav:
  - 'index.md'
  - Code Reference:
    - 'pages.md'
    - 'components.md'
    - 'store.md'

