site_name: ipywidgets_todo Documentation

theme:
  name: "material"
  
plugins:
  - mkdocstrings

use_directory_urls: false

nav:
  - README.md
  - Code Reference:
    - 'pages.md'
    - 'components.md'
    - 'store.md'